services:
  backend:
    container_name: smit_backend
    build:
      dockerfile: ./Dockerfile
      context: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: smit_db
    image: postgres:16.1-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - 5432
    env_file:
      - .env

  #  pgbackups:
  #    image: prodrigestivill/postgres-backup-local
  #    container_name: smit_backups
  #    restart: always
  #    user: postgres:postgres
  #    volumes:
  #      - /var/opt/pgbackups:/backups
  #    links:
  #      - db
  #    depends_on:
  #      - db
  #    env_file:
  #      - .env

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    expose:
      - 2181
    env_file:
      - .env

  kafka:
    container_name: smit_kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    env_file:
      - .env

  kafka-ui:
    container_name: smit_kafka_ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  pgdata:
